$file = 'c:\Users\22737\source\repos\FactionGearModification\1.6\Languages\Korean\Keyed\FactionGearCustomizer.xml'
$xml = [xml](Get-Content $file -Encoding UTF8)

$translations = @{
    # === General UI ===
    "yc's Faction Editor" = "yc의 진영 편집기"
    "Factions" = "진영"
    "Item Library" = "아이템 라이브러리"
    "Advanced" = "고급"
    "Simple" = "간단"
    "Preview" = "미리보기"
    "Group Preview" = "그룹 미리보기"
    "Seed" = "시드"
    "Draws" = "추첨"
    "Rebuild" = "재생성"
    "Generate Portraits" = "초상화 생성"
    "Clear All" = "모두 지우기"
    "Clear" = "지우기"
    "Apply to Others" = "다른 항목에 적용"
    "Yes" = "예"
    "Cancel" = "취소"
    "Save" = "저장"
    "Save As" = "다른 이름으로 저장"
    "Load" = "불러오기"
    "Delete" = "삭제"
    "Export" = "내보내기"
    "Import" = "가져오기"
    "Apply" = "적용"
    "Reset" = "초기화"
    "Close" = "닫기"
    "Confirm" = "확인"
    "Add Apparel" = "의류 추가"
    "Add Weapon" = "무기 추가"
    "Add Hediff" = "상태 효과 추가"
    "Pick Color" = "색상 선택"
    "Set Color" = "색상 설정"
    "Select Item" = "아이템 선택"
    "Select Hediff" = "상태 효과 선택"
    "Show" = "표시"
    "Hide" = "숨기기"
    "Disabled" = "비활성화"
    "All" = "전체"
    "None" = "없음"
    "Invert" = "반전"
    "Default" = "기본값"
    "Random Material" = "무작위 재료"
    "Selected Gear" = "선택된 장비"
    "Advanced Settings" = "고급 설정"
    "Layer Preview" = "레이어 미리보기"
    "General Overrides" = "일반 설정"
    "Specific Apparel (Adv)" = "특정 의류 (고급)"
    "Specific Weapons (Adv)" = "특정 무기 (고급)"
    "Forced Hediffs" = "강제 상태 효과"
    "Inventory" = "인벤토리"
    "Add Item" = "아이템 추가"
    "Quick Add" = "빠른 추가"
    "Default Count" = "기본 수량"
    "Default Chance" = "기본 확률"
    "Skip Existing" = "기존 항목 건너뛰기"
    "Already Added" = "이미 추가됨"
    "Add Selected" = "선택 추가"
    "Items" = "아이템"
    "Count" = "수량"
    "Advanced/Specific Items" = "고급/특정 아이템"
    "Edit Faction" = "진영 편집"
    "Mod Filter" = "모드 필터"
    "Category Filter" = "카테고리 필터"
    "Category: All" = "카테고리: 전체"
    "Apparel Color:" = "의류 색상:"
    "Item Quality" = "아이템 품질"
    "Apparel Budget" = "의류 예산"
    "Weapon Budget" = "무기 예산"
    "Tech Level Limit" = "기술 수준 제한"
    "Weapon Quality" = "무기 품질"
    "Biocode Chance" = "바이오코드 확률"
    "Apparel Biocode Chance" = "의류 바이오코드 확률"
    "Biocode" = "바이오코드"
    "Force Naked" = "강제 나체"
    "Force Only Selected" = "선택한 항목만 강제"
    "Force Override Hediffs" = "상태 효과 강제 적용"
    "Ranged" = "원거리"
    "Melee" = "근접"
    "Armors" = "방어구"
    "Clothes" = "의복"
    "Others" = "기타"
    "General" = "일반"
    "Apparel" = "의류"
    "Weapons" = "무기"
    "Hediffs" = "상태 효과"
    "Head" = "머리"
    "Torso" = "몸통"
    "Shoulders" = "어깨"
    "Arms" = "팔"
    "Hands" = "손"
    "Waist" = "허리"
    "Legs" = "다리"
    "Feet" = "발"
    "Skin" = "피부"
    "Mid" = "중간"
    "Settings Saved!" = "설정 저장됨!"
    "Settings Discarded." = "설정이 취소되었습니다."
    "Changelog" = "변경 로그"

    # === Presets ===
    "Presets" = "프리셋"
    "Options" = "옵션"
    "Preset Manager" = "프리셋 관리자"
    "Preset Updated" = "프리셋 업데이트됨"
    "Preset Saved" = "프리셋 저장됨"

    # === Raid Points (new keys) ===
    "Auto-Calculate Raid Points" = "레이드 포인트 자동 계산"
    "Raid points auto-calculated based on gear value." = "장비 가치에 따라 레이드 포인트가 자동 계산되었습니다."
    "Auto-Modify Raid Points" = "레이드 포인트 자동 수정"
    "Calculate raid points based on pawn gear value for elite-compressed raids to reduce performance load." = "폰 장비 가치에 따라 레이드 포인트를 계산하여 엘리트 압축 레이드로 성능 부하를 줄입니다."

    # === Common terms ===
    "Settings" = "설정"
    "Name" = "이름"
    "Description" = "설명"
    "Weight" = "가중치"
    "Value" = "가치"
    "Damage" = "피해"
    "Range" = "사거리"
    "DPS" = "DPS"
    "Sharp Armor" = "예리 방어"
    "Blunt Armor" = "둔기 방어"
    "Market Value" = "시장 가치"
    "Mass" = "무게"
    "Search" = "검색"
    "Edit" = "편집"
    "Remove" = "제거"
    "Quality" = "품질"
    "Material" = "재료"
    "Color" = "색상"
    "Budget" = "예산"
    "Tech Level" = "기술 수준"
    "Undo" = "실행 취소"
    "Redo" = "다시 실행"
    "History" = "기록"
    "Refresh" = "새로고침"
    "Version" = "버전"
    "Mod" = "모드"
    "Faction" = "진영"
    "Pawn" = "폰"
    "Chance" = "확률"
    "Severity" = "심각도"
    "Parts" = "부위"
    "Shell" = "외투"
    "Belt" = "허리띠"
    "Over" = "겉옷"
    "Reroll" = "재생성"
    "Retry" = "재시도"
    "Rotate" = "회전"
    "Total" = "합계"
    "Browse" = "찾아보기"
    "Active" = "활성"
    "Unknown" = "알 수 없음"
    "Category" = "카테고리"
}

$count = 0
foreach ($node in $xml.LanguageData.ChildNodes) {
    if ($node.NodeType -eq 'Element') {
        $enValue = $node.InnerText.Trim()
        if ($translations.ContainsKey($enValue)) {
            $node.InnerText = $translations[$enValue]
            $count++
        }
    }
}

$xml.Save($file)
Write-Host "Translated $count keys to Korean."
